EXTRACT_QUERY = """
WITH bacterie_resistant AS (
    SELECT *
    FROM ORAGLIMS.ANTIBIOTICRESULT ar
    WHERE ar.ABRS_RISREPORTVALUE = 3
    ORDER BY ar.ABRS_AVAILABILITYTIME DESC, ar.ABRS_ID
    FETCH FIRST 10000 ROWS ONLY
)
SELECT
    SYSDATE,
    idnt.IDNT_CODE,
    p.PRSN_INTERNALID,
    p.PRSN_LASTNAME,
    p.PRSN_FIRSTNAME,
    p.PRSN_BIRTHDATE,
    p.PRSN_SEX,
    p.PRSN_DECEASETIME,

    e.ENCT_EXTERNALID,
    e.ENCT_PERSON,
    e.ENCT_INSTITUTION,
    e.ENCT_TYPE,
    e.ENCT_STARTTIME,
    e.ENCT_ENDTIME,

    o.ORD_ID,
    o.ORD_INTERNALID,
    o.ORD_SHORTID,
    o.ORD_DESCRIPTION,
    o.ORD_STATUS,
    o.ORD_LOWESTOBJECTTIME,
    o.ORD_PRESCRIPTIONTIME,
    o.ORD_RECEIPTTIME,
    o.ORD_COMPLETIONTIME,
    r.RSLT_STATUS,

    crsp.CRSP_INTERNALID,
    crsp.CRSP_NAME,
    d.DEPT_NAME,

    spmn.SPMN_ID,
    spmn.SPMN_INTERNALID,
    m.MAT_SHORTNAME,
    md.ML18_TRANSLATION,
    spmn.SPMN_RECEIPTTIME,
    spmn.SPMN_STATUS,

    i.ISOL_ID,
    i.ISOL_STATUS,
    i.ISOL_AVAILABILITYTIME,
    i.ISOL_VALIDATIONTIME,
    i.ISOL_CONFIRMATIONTIME,

    morg.MORG_ID,
    morg.MORG_NAME,

    a.AB_ID,
    a.AB_MNEMONIC,
    a.AB_NAME,

    br.ABRS_ID,
    br.ABRS_RISREPORTVALUE,
    br.ABRS_MICRAWVALUE,
    br.ABRS_AVAILABILITYTIME,
    br.ABRS_PANEL,
    ap.ABP_NAME,
    br.ABRS_STATUS

FROM bacterie_resistant br

JOIN ORAGLIMS.ISOLATION i
    ON br.ABRS_ISOLATION = i.ISOL_ID

JOIN ORAGLIMS.SPECIMEN spmn
    ON i.ISOL_SPECIMEN = spmn.SPMN_ID

JOIN ORAGLIMS.RESULT r
    ON r.RSLT_SPECIMEN = spmn.SPMN_ID

JOIN ORAGLIMS.ORDER_ o
    ON r.RSLT_ORDER = o.ORD_ID

JOIN ORAGLIMS.ENCOUNTER e
    ON e.ENCT_ID = o.ORD_ENCOUNTER

JOIN ORAGLIMS.INSTITUTION inst
    ON e.ENCT_INSTITUTION = inst.INST_ID
   AND inst.INST_ID = 470

JOIN ORAGLIMS.MICROORGANISM morg
    ON i.ISOL_MICROORGANISM = morg.MORG_ID

JOIN ORAGLIMS.ANTIBIOTIC a
    ON br.ABRS_ANTIBIOTIC = a.AB_ID

JOIN ORAGLIMS.PERSON p
    ON e.ENCT_PERSON = p.PRSN_ID

LEFT JOIN ORAGLIMS.IDENTIFICATION idnt
    ON p.PRSN_CORRESPONDENT = idnt.IDNT_TARGET
   AND idnt.IDNT_ENDDATE IS NULL

LEFT JOIN ORAGLIMS.DEPARTMENT d
    ON o.ORD_DEPARTMENT = d.DEPT_ID

LEFT JOIN ORAGLIMS.CORRESPONDENT crsp
    ON o.ORD_ISSUER = crsp.CRSP_ID

LEFT JOIN ORAGLIMS.MATERIAL m
    ON spmn.SPMN_MATERIAL = m.MAT_ID

LEFT JOIN ORAGLIMS.MATERIALDESCRIPTION md
    ON spmn.SPMN_MATERIAL = md.ML18_DESCRIPTION

LEFT JOIN ORAGLIMS.ANTIBIOTICPANEL ap
    ON br.ABRS_PANEL = ap.ABP_ID

ORDER BY
    i.ISOL_VALIDATIONTIME DESC,
    p.PRSN_INTERNALID,
    i.ISOL_ID,
    a.AB_MNEMONIC

FETCH FIRST 100 ROWS ONLY
"""
