GAM_EXTRACT_QUERY = """SELECT
    PP.PAT_IPP AS IPP,
    PP.IEP_IDE AS IEP,
    HOS.HOSDATENT as EVENT_TIME,
    HOS.HOSDATENT AS DATE_ENTREE_SEJOUR,
    HOS.HOSDATSOR AS DATE_SORTIE_SEJOUR,
    HOS.UFOCODIDEENT UF_ENTREE,
    HOS.UFOCODIDESOR UF_SORTIE,
    PRP.PA_RES_PAT_IDE AS ID_MOUVEMENT,
    UF.SVCLIB AS LIBELLE_SERVICE,
    UF.ETAB,
    UF.ETBLIB,
    UF.UMLIB,
    PRP.LIE_ETB_NUM,
    PRP.LIE_BAT_NUM,
    PRP.ETG_NUM,
    PRP.LIE_NUM,
    PRP.LIT_NUM,
    PRP.PA_RES_PAT_PER_DEB AS DATE_DEBUT_MOUVEMENT,
    PRP.PA_RES_PAT_PER_FIN AS DATE_FIN_MOUVEMENT
FROM AM01.HOS HOS
JOIN PA_INS01.PA_PAS PP
    ON HOS.HOSCODIDEHOS = PP.IEP_IDE
JOIN PA_INS01.PA_RES_PAT PRP
    ON PRP.PAS_IPS = PP.PAS_IPS
LEFT JOIN NOYLOC.BR_BO_UF UF
    ON PRP.UFO_IDE = UF.UFONUM
WHERE PP.PAT_IPP ='000167825'
ORDER BY HOS.HOSDATENT DESC
"""
