WITH pcr_dedup AS (
    SELECT
        o.ORD_ID,
        prop.PROP_SHORTNAME     AS libelle_gene,
        res.RSLT_RAWVALUE       AS resultat_pcr,
        res.RSLT_VALIDATIONTIME AS date_validation_pcr,
        res.RSLT_STATUS         AS statut_resultat,
        -- Prelevement PCR, rattache via RESULT.RSLT_SPECIMEN
        sp.SPMN_INTERNALID,
        sp.SPMN_SAMPLINGTIME,
        sp.SPMN_RECEIPTTIME,
        ROW_NUMBER() OVER (L
            PARTITION BY o.ORD_ID, prop.PROP_SHORTNAME
            ORDER BY res.RSLT_VALIDATIONTIME DESC NULLS LAST
        ) AS rn
    FROM ORAGLIMS.ORDER_ o
    INNER JOIN ORAGLIMS.REQUEST  req  ON o.ORD_ID          = req.RQST_ORDER
    INNER JOIN ORAGLIMS.RESULT   res  ON req.RQST_RESULT   = res.RSLT_ID
    INNER JOIN ORAGLIMS.PROPERTY prop ON res.RSLT_PROPERTY = prop.PROP_ID
    LEFT  JOIN ORAGLIMS.SPECIMEN sp   ON sp.SPMN_ID        = res.RSLT_SPECIMEN
    WHERE prop.PROP_SHORTNAME IN ('OXA48', 'KPC', 'NDM', 'VIM et ou  IMP')
)

-- BRANCHE 1 : lignes PCR (une par gene), focalisee sur les genes.
-- Les trois colonnes de prelevement sont desormais remontees ;
-- les colonnes microbio restent NULL (une PCR n'a ni germe cultive,
-- ni antibiogramme, ni test d'isolement).
SELECT
    i.IDNT_CODE,
    p.PRSN_ID,
    p.PRSN_INTERNALID,
    p.PRSN_LASTNAME,
    p.PRSN_FIRSTNAME,
    p.PRSN_BIRTHDATE,
    p.PRSN_SEX,
    o.ORD_INTERNALID,
    pcr.SPMN_INTERNALID,
    pcr.SPMN_SAMPLINGTIME,
    pcr.SPMN_RECEIPTTIME,
    NULL AS ML18_TRANSLATION,
    NULL AS ML86_TRANSLATION,
    NULL AS ML07_TRANSLATION,
    NULL AS MORG_NAME,
    NULL AS AB_MNEMONIC,
    NULL AS AB_NAME,
    NULL AS ABRS_RISREPORTVALUE,
    NULL AS ABRS_STATUS,
    NULL AS MOT_DESCRIPTION,
    NULL AS ISOT_VALUE,
    pcr.libelle_gene,
    pcr.resultat_pcr,
    pcr.date_validation_pcr,
    pcr.statut_resultat AS RSLT_STATUS
FROM ORAGLIMS.PERSON p
INNER JOIN ORAGLIMS.ENCOUNTER e ON e.ENCT_PERSON = p.PRSN_ID
INNER JOIN ORAGLIMS.ORDER_ o    ON o.ORD_ENCOUNTER = e.ENCT_ID
LEFT JOIN ORAGLIMS.IDENTIFICATION i ON p.PRSN_CORRESPONDENT = i.IDNT_TARGET
INNER JOIN pcr_dedup pcr ON pcr.ORD_ID = o.ORD_ID AND pcr.rn = 1
WHERE i.IDNT_CODE IN ('000203765', '000381287')

UNION ALL

-- BRANCHE 2 : lignes culture / microbio, avec conditions de detection.
-- Le NOT EXISTS est retire : un dossier ayant une PCR remonte aussi
-- sa culture (PCR et culture coexistent sur un meme ORD_INTERNALID).
SELECT
    i.IDNT_CODE,
    p.PRSN_ID,
    p.PRSN_INTERNALID,
    p.PRSN_LASTNAME,
    p.PRSN_FIRSTNAME,
    p.PRSN_BIRTHDATE,
    p.PRSN_SEX,
    o.ORD_INTERNALID,
    s.SPMN_INTERNALID,
    s.SPMN_SAMPLINGTIME,
    s.SPMN_RECEIPTTIME,
    mat_desc.ML18_TRANSLATION,
    ml86.ML86_TRANSLATION,
    ch_desc.ML07_TRANSLATION,
    morg.MORG_NAME,
    anti.AB_MNEMONIC,
    anti.AB_NAME,
    abrs.ABRS_RISREPORTVALUE,
    abrs.ABRS_STATUS,
    m.MOT_DESCRIPTION,
    i2.ISOT_VALUE,
    NULL AS libelle_gene,
    NULL AS resultat_pcr,
    NULL AS date_validation_pcr,
    r.RSLT_STATUS
FROM ORAGLIMS.PERSON p
INNER JOIN ORAGLIMS.ENCOUNTER e ON e.ENCT_PERSON = p.PRSN_ID
INNER JOIN ORAGLIMS.ORDER_ o    ON o.ORD_ENCOUNTER = e.ENCT_ID
INNER JOIN ORAGLIMS.RESULT r    ON r.RSLT_ORDER = o.ORD_ID
INNER JOIN ORAGLIMS.SPECIMEN s  ON s.SPMN_ID = r.RSLT_SPECIMEN
LEFT JOIN ORAGLIMS.IDENTIFICATION i           ON p.PRSN_CORRESPONDENT = i.IDNT_TARGET
LEFT JOIN ORAGLIMS.MATERIAL mat               ON s.SPMN_MATERIAL = mat.MAT_ID
LEFT JOIN ORAGLIMS.MATERIALDESCRIPTION mat_desc ON mat_desc.ML18_DESCRIPTION = mat.MAT_ID
LEFT JOIN ORAGLIMS.SPECIMENVARIABLE spmv      ON s.SPMN_ID = spmv.SPMV_SPECIMEN
LEFT JOIN ORAGLIMS.MATERIALVARIABLECHOICE mvc ON spmv.SPMV_CHOICE = mvc.MTVC_ID
LEFT JOIN ORAGLIMS.MATRIALVARIABLCHOICVALU ml86 ON ml86.ML86_VALUE = mvc.MTVC_ID
LEFT JOIN ORAGLIMS.CHOICE ch                  ON r.RSLT_CHOICE = ch.CHC_ID
LEFT JOIN ORAGLIMS.CHOICEDESCRIPTION ch_desc  ON ch.CHC_ID = ch_desc.ML07_DESCRIPTION
LEFT JOIN ORAGLIMS.ISOLATION isol             ON r.RSLT_SPECIMEN = isol.ISOL_SPECIMEN
LEFT JOIN ORAGLIMS.MICROORGANISM morg         ON isol.ISOL_MICROORGANISM = morg.MORG_ID
LEFT JOIN ORAGLIMS.ISOLATIONTEST i2           ON isol.ISOL_ID = i2.ISOT_ISOLATION
LEFT JOIN ORAGLIMS.MICROORGANISMTEST m        ON m.MOT_ID = i2.ISOT_TEMPLATE
LEFT JOIN ORAGLIMS.ANTIBIOTICRESULT abrs      ON isol.ISOL_ID = abrs.ABRS_ISOLATION
LEFT JOIN ORAGLIMS.ANTIBIOTIC anti            ON abrs.ABRS_ANTIBIOTIC = anti.AB_ID
WHERE
(
    UPPER(ml86.ML86_TRANSLATION) LIKE '%CARBA%'
    OR UPPER(ml86.ML86_TRANSLATION) LIKE '%ERV'
    OR (
        UPPER(morg.MORG_NAME) LIKE '%FAECIUM%'
        AND UPPER(anti.AB_NAME) LIKE '%VANCO%'
        AND abrs.ABRS_RISREPORTVALUE = 1
    )
    OR (
        (UPPER(m.MOT_DESCRIPTION) LIKE '%CARBA%'
         OR UPPER(m.MOT_DESCRIPTION) LIKE '%ERV%')
        AND (UPPER(i2.ISOT_VALUE) LIKE '%POS%'
             OR UPPER(i2.ISOT_VALUE) = 'OUI')
    )
)
AND i.IDNT_CODE IN ('000203765', '000381287')