GLIMS_EXTRACT_QUERY = """SELECT
    i.IDNT_CODE,
    p.PRSN_ID,
    p.PRSN_INTERNALID,
    p.PRSN_LASTNAME,
    p.PRSN_FIRSTNAME,
    p.PRSN_BIRTHDATE,
    p.PRSN_SEX,
    o.ORD_INTERNALID,
    s.SPMN_INTERNALID,
    s.SPMN_SAMPLINGTIME,
    s.SPMN_RECEIPTTIME,
    mat_desc.ML18_TRANSLATION,
    ml86.ML86_TRANSLATION,
    ch_desc.ML07_TRANSLATION,
    morg.MORG_NAME,
    anti.AB_MNEMONIC,
    anti.AB_NAME,
    abrs.ABRS_RISREPORTVALUE,
    abrs.ABRS_STATUS,
    m.MOT_DESCRIPTION,
    i2.ISOT_VALUE
FROM ORAGLIMS.PERSON p
INNER JOIN ORAGLIMS.ENCOUNTER e ON e.ENCT_PERSON = p.PRSN_ID
INNER JOIN ORAGLIMS.ORDER_ o ON o.ORD_ENCOUNTER = e.ENCT_ID
INNER JOIN ORAGLIMS.RESULT r ON r.RSLT_ORDER = o.ORD_ID
INNER JOIN ORAGLIMS.SPECIMEN s ON s.SPMN_ID = r.RSLT_SPECIMEN
LEFT JOIN ORAGLIMS.IDENTIFICATION i ON p.PRSN_CORRESPONDENT = i.IDNT_TARGET
LEFT JOIN ORAGLIMS.MATERIAL mat ON s.SPMN_MATERIAL = mat.MAT_ID
LEFT JOIN ORAGLIMS.MATERIALDESCRIPTION mat_desc ON mat_desc.ML18_DESCRIPTION = mat.MAT_ID
LEFT JOIN ORAGLIMS.SPECIMENVARIABLE spmv ON s.SPMN_ID = spmv.SPMV_SPECIMEN
LEFT JOIN ORAGLIMS.MATERIALVARIABLECHOICE mvc ON spmv.SPMV_CHOICE = mvc.MTVC_ID
LEFT JOIN ORAGLIMS.MATRIALVARIABLCHOICVALU ml86 ON ml86.ML86_VALUE = mvc.MTVC_ID
LEFT JOIN ORAGLIMS.CHOICE ch ON r.RSLT_CHOICE = ch.CHC_ID
LEFT JOIN ORAGLIMS.CHOICEDESCRIPTION ch_desc ON ch.CHC_ID = ch_desc.ML07_DESCRIPTION
LEFT JOIN ORAGLIMS.ISOLATION isol ON r.RSLT_SPECIMEN = isol.ISOL_SPECIMEN
LEFT JOIN ORAGLIMS.MICROORGANISM morg 
    ON isol.ISOL_MICROORGANISM = morg.MORG_ID
LEFT JOIN ORAGLIMS.ISOLATIONTEST i2 
    ON isol.ISOL_ID = i2.ISOT_ISOLATION
LEFT JOIN ORAGLIMS.MICROORGANISMTEST m 
    ON m.MOT_ID = i2.ISOT_TEMPLATE
LEFT JOIN ORAGLIMS.ANTIBIOTICRESULT abrs 
    ON isol.ISOL_ID = abrs.ABRS_ISOLATION
LEFT JOIN ORAGLIMS.ANTIBIOTIC anti 
    ON abrs.ABRS_ANTIBIOTIC = anti.AB_ID
WHERE 
(
    UPPER(ml86.ML86_TRANSLATION) LIKE '%CARBA%'
    OR UPPER(ml86.ML86_TRANSLATION) LIKE '%ERV'
    OR (
        UPPER(morg.MORG_NAME) LIKE '%FAECIUM%'
        AND UPPER(anti.AB_NAME) LIKE '%VANCO%'
        AND abrs.ABRS_RISREPORTVALUE = 1
    )
    OR (
        (UPPER(m.MOT_DESCRIPTION) LIKE '%CARBA%'
         OR UPPER(m.MOT_DESCRIPTION) LIKE '%ERV%')
        AND (UPPER(i2.ISOT_VALUE) LIKE '%POS%'
             OR UPPER(i2.ISOT_VALUE) = 'OUI')
    )
   
)
FETCH FIRST 200 ROWS ONLY
"""
